// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimulacaoCredito.Infrastructure.Data;

#nullable disable

namespace SimulacaoCredito.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250822043647_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimulacaoCredito.Domain.Entities.Parcela", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<long>("SimulacaoId")
                        .HasColumnType("bigint");

                    b.Property<byte>("TipoAmortizacao")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("ValorAmortizacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorJuros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPrestacao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoId", "TipoAmortizacao")
                        .HasDatabaseName("IX_Parcela_SimulacaoId_TipoAmortizacao");

                    b.ToTable("Parcela", "dbo");
                });

            modelBuilder.Entity("SimulacaoCredito.Domain.Entities.Simulacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Prazo")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxaJuros")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("ValorDesejado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalParcelas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProduto")
                        .HasDatabaseName("IX_Simulacao_CodigoProduto");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("IX_Simulacao_DataCriacao");

                    b.ToTable("Simulacao", "dbo");
                });

            modelBuilder.Entity("SimulacaoCredito.Domain.Entities.Parcela", b =>
                {
                    b.HasOne("SimulacaoCredito.Domain.Entities.Simulacao", "Simulacao")
                        .WithMany("Parcelas")
                        .HasForeignKey("SimulacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("SimulacaoCredito.Domain.Entities.Simulacao", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
